# Use this config file for development to cut down on render times.

baseurl: /home/david/Projects/cheesy.at/_site
destination: /home/david/Projects/cheesy.at/_site
future: true
profile: true
trace: true
limit_posts: 10

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - cheesycompose/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - _fotos/arbeit/
  - _fotos/ausfluege/2000-2009/
  - _fotos/ausfluege/2010-2019/
  - _fotos/ausfluege/2020-2/
  - _fotos/urlaub/
  - _fotos/sonstiges/
  - _fotos/events/
  - _fotos/kunstwerke/
  - _fotos/leben-in-belfast/
  - _rezepte/fruehstueck
  - _rezepte/baeckereien
  - _rezepte/hauptspeisen
  - _rezepte/nachspeisen
  - _rezepte/beilagen-und-sonstiges
  - _rezepte/vorspeisen-und-suppen
  - _rezepte/smoothies-und-drinks
  - _rezepte/brot-backen
