# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Christines Blog
email: christine@cheesy.at
description: >- # this means to ignore newlines until "baseurl:"
  Du bist hier auf der privaten Homepage von Christine Schmitt gelandet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://test.cheesy.at" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true
paginate: 5
paginate_path: "/home/page:num/"

strict_front_matter: true

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-paginate
  - jekyll-category-pages
  - jekyll-include-cache
  - cheesy-gallery

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - cheesycompose/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - image_map.yaml

jekyll_analytics:
  Plausible:
    domain: 'test.cheesy.at'
    source: 'https://plausible.black.co.at/js/plausible.outbound-links.js'
    404_tracking: true

defaults:
  - scope:
      path: ""
    values:
      author:
        display_name: cheesy
        login: cheesy
        email: christine@cheesy.at
        url: http://www.cheesy.at/

collections:
  posts:
    # adjust to old wordpress pattern for preserving old links
    permalink: /:year/:month/:title/
  passets:
    cheesy-gallery: true
  fotos:
    cheesy-gallery: true
  rezepte:
    cheesy-gallery: true
